# Generated by Django 3.2.7 on 2021-10-07 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flux', '0003_remove_review_ticket'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
