# Generated by Django 3.2.7 on 2021-10-07 09:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('flux', '0008_ticket_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='time_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
